//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        public int IdFaktury { get; set; }
        public string NrFaktury { get; set; }
        public Nullable<int> IdProduktuUslugi { get; set; }
        public Nullable<int> IdRodzajuPlatnosci { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public Nullable<decimal> KwotaNetto { get; set; }
        public Nullable<decimal> KwotaBrutto { get; set; }
        public Nullable<int> Podatek { get; set; }
        public Nullable<int> IloscSztuk { get; set; }
        public Nullable<int> IdStatusuFaktury { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual ProduktyUslugi ProduktyUslugi { get; set; }
        public virtual RodzajePlatnosci RodzajePlatnosci { get; set; }
        public virtual StatusFaktury StatusFaktury { get; set; }
    }
}
