//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzytkownicy()
        {
            this.Klienci = new HashSet<Klienci>();
            this.Projekty = new HashSet<Projekty>();
            this.Zadania1 = new HashSet<Zadania>();
            this.Zespoly1 = new HashSet<Zespoly>();
            this.Zespoly2 = new HashSet<Zespoly>();
            this.Zespoly3 = new HashSet<Zespoly>();
            this.Zespoly4 = new HashSet<Zespoly>();
            this.Zespoly5 = new HashSet<Zespoly>();
        }
    
        public int IdUzytkownika { get; set; }
        public Nullable<int> IdProjektu { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Email { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<int> IdSzkolenia { get; set; }
        public Nullable<int> IdZaespolu { get; set; }
        public Nullable<int> IdZadania { get; set; }
        public string Rola { get; set; }
        public Nullable<int> IdKlienta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klienci> Klienci { get; set; }
        public virtual Klienci Klienci1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekty> Projekty { get; set; }
        public virtual Projekty Projekty1 { get; set; }
        public virtual Szkolenia Szkolenia { get; set; }
        public virtual Zadania Zadania { get; set; }
        public virtual Zespoly Zespoly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadania> Zadania1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zespoly> Zespoly1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zespoly> Zespoly2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zespoly> Zespoly3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zespoly> Zespoly4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zespoly> Zespoly5 { get; set; }
    }
}
