//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        public int IdZamowienia { get; set; }
        public Nullable<int> IdStatusu { get; set; }
        public Nullable<System.DateTime> DataZamowienia { get; set; }
        public Nullable<decimal> Kwota { get; set; }
        public Nullable<int> IdProduktuUslugi { get; set; }
        public Nullable<int> IloscSztuk { get; set; }
    
        public virtual ProduktyUslugi ProduktyUslugi { get; set; }
        public virtual Statusy Statusy { get; set; }
    }
}
