//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZapytaniaKlientow
    {
        public int IdZapytania { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public Nullable<int> IdStatusu { get; set; }
        public Nullable<System.DateTime> DataZapytania { get; set; }
        public string TrescZapytania { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Statusy Statusy { get; set; }
    }
}
